places =
[{"placeName":"Jaxson's Ice Cream Parlor & Restaurant","descrip":"A 50+ year old ice cream parlor know for its homemade ice cream, massive servings, and unique décor.","latitude":26.04286,"longitude":-80.143402},
{"placeName":"The Ernest Hemingway Home and Museum","descrip":"See the home of the famous writer, his family, and the descendents of his many six-toed cats.","latitude":24.551189,"longitude":-81.800652},
{"placeName":"South Beach","descrip":"One of the most popular beaches in Florida, you won't be disapointed by its amazing restaurants, beautiful art, and of course, stunning coastline.","latitude":25.780532,"longitude":-80.130566},
{"placeName":"Vizcaya Museum and Gardens","descrip":"Visit the 35-acre property to jump into Miami's past and see the stunning gardens.","latitude":25.744452,"longitude":-80.210403},
{"placeName":"Morikami Museum & Japanese Gardens","descrip":"Travel around the world in these Japanese-inspired gardens for a zen experience.","latitude":26.42976,"longitude":-80.15679},
{"placeName":"Lion Country Safari","descrip":"It won't feel like Loxahatchee anymore when an ostrich is staring through your window! This wildlife preserve and amusement park is full to delight!","latitude":26.71618,"longitude":-80.32226},
{"placeName":"Seminole Hard Rock Hotel & Casino","descrip":"Win big at this hotel, casino, and shopping center as your eat at you live the highlife.","latitude":26.050341,"longitude":-80.208038},
{"placeName":"Venetian Pool","descrip":"Swim in style at these historic, spring-filled pools in Coral Gables.","latitude":25.745701,"longitude":-80.273392},
{"placeName":"Sawgrass Mills Mall","descrip":"Shop at outlets for tons of the most popular stores out there at one of the largest outlet malls in the country!","latitude":26.14621,"longitude":-80.324692},
{"placeName":"Fort Lauderdale Beach","descrip":"Spend the day sun tanning or walk down the boardwalk at he beaches in this hip city!","latitude":26.14298,"longitude":-80.10242},
{"placeName":"Festival Marketplace","descrip":"Scour this always full flee market to find what hidden treasures await.","latitude":26.27431,"longitude":-80.15859},
{"placeName":"Wynwood Walls","descrip":"Take pictures that will make your friends jealous in this artistic neighborhood.","latitude":25.801138,"longitude":-80.199326},
{"placeName":"John Pennekamp Coral Reef State Park","descrip":"Snorkle in the lively reefs of this fantastic state park!","latitude":25.124741,"longitude":-80.407623},
{"placeName":"Museum of Discovery and Science","descrip":"The whole family will love this interactive and fun-filled science museum and IMAX theater.","latitude":26.120831,"longitude":-80.148003},
{"placeName":"Miami Seaquarium","descrip":"Play with the penguins or see the orca shows at this fun aquarium!","latitude":25.736309,"longitude":-80.165466},
{"placeName":"Butterfly World","descrip":"View the majestic home of tons of butterflies as you learn more bout them!","latitude":26.27402,"longitude":-80.17346},
{"placeName":"Domino Park","descrip":"Emerse yourself in Cuban culture this park on the famous Calle Ocho.","latitude":25.781019,"longitude":-80.220039},
{"placeName":"Zoo Miami","descrip":"Walk through wildlife exhibits to learn about different animals!","latitude":25.611471,"longitude":-80.398232},
{"placeName":"The Town Center at Boca Raton","descrip":"Scroll through this luxorious, upscale mall to shop in style.","latitude":26.364346,"longitude":-80.133507},
{"placeName":"Henry Morrison Flagler Museum","descrip":"Turn back time to the Gilded Age as you explore this resplendent manor.","latitude":26.713711,"longitude":-80.04361}]
